var AWS = require('../core');

AWS.SimpleWorkflow.api = [
  { n:'CountClosedWorkflowExecutions' },
  { n:'CountOpenWorkflowExecutions' },
  { n:'CountPendingActivityTasks' },
  { n:'CountPendingDecisionTasks' },
  { n:'DeprecateActivityType' },
  { n:'DeprecateDomain' },
  { n:'DeprecateWorkflowType' },
  { n:'DescribeActivityType' },
  { n:'DescribeDomain' },
  { n:'DescribeWorkflowExecution' },
  { n:'DescribeWorkflowType' },
  { n:'GetWorkflowExecutionHistory' },
  { n:'ListActivityTypes' },
  { n:'ListClosedWorkflowExecutions' },
  { n:'ListDomains' },
  { n:'ListOpenWorkflowExecutions' },
  { n:'ListWorkflowTypes' },
  { n:'PollForActivityTask' },
  { n:'PollForDecisionTask' },
  { n:'RecordActivityTaskHeartbeat' },
  { n:'RegisterActivityType' },
  { n:'RegisterDomain' },
  { n:'RegisterWorkflowType' },
  { n:'RequestCancelWorkflowExecution' },
  { n:'RespondActivityTaskCanceled' },
  { n:'RespondActivityTaskCompleted' },
  { n:'RespondActivityTaskFailed' },
  { n:'RespondDecisionTaskCompleted' },
  { n:'SignalWorkflowExecution' },
  { n:'StartWorkflowExecution' },
  { n:'TerminateWorkflowExecution' }
];
