// Generated by CoffeeScript 1.12.3
(function() {
  var AWS, helpers;

  helpers = require('../helpers');

  AWS = helpers.AWS;

  describe('AWS.STS', function() {
    var sts;
    sts = null;
    beforeEach(function() {
      return sts = new AWS.STS();
    });
    describe('credentialsFrom', function() {
      it('returns null if no data is provided', function() {
        return expect(sts.credentialsFrom(null)).to.equal(null);
      });
      it('creates a TemporaryCredentials object with hydrated data', function() {
        var creds;
        creds = sts.credentialsFrom({
          Credentials: {
            AccessKeyId: 'KEY',
            SecretAccessKey: 'SECRET',
            SessionToken: 'TOKEN',
            Expiration: new Date(0)
          }
        });
        expect(creds instanceof AWS.TemporaryCredentials);
        expect(creds.accessKeyId).to.equal('KEY');
        expect(creds.secretAccessKey).to.equal('SECRET');
        expect(creds.sessionToken).to.equal('TOKEN');
        expect(creds.expireTime).to.eql(new Date(0));
        return expect(creds.expired).to.equal(false);
      });
      return it('updates an existing Credentials object with hydrated data', function() {
        var creds, data;
        data = {
          Credentials: {
            AccessKeyId: 'KEY',
            SecretAccessKey: 'SECRET',
            SessionToken: 'TOKEN',
            Expiration: new Date(0)
          }
        };
        creds = new AWS.Credentials;
        sts.credentialsFrom(data, creds);
        expect(creds).to.be.instanceOf(AWS.Credentials);
        expect(creds.accessKeyId).to.equal('KEY');
        expect(creds.secretAccessKey).to.equal('SECRET');
        expect(creds.sessionToken).to.equal('TOKEN');
        expect(creds.expireTime).to.eql(new Date(0));
        return expect(creds.expired).to.equal(false);
      });
    });
    describe('assumeRoleWithWebIdentity', function() {
      var service;
      service = new AWS.STS;
      it('sends an unsigned POST request', function() {
        var params;
        helpers.mockHttpResponse(200, {}, '{}');
        params = {
          RoleArn: 'ARN',
          RoleSessionName: 'NAME',
          WebIdentityToken: 'TOK'
        };
        return service.assumeRoleWithWebIdentity(params, function() {
          var hr;
          hr = this.request.httpRequest;
          expect(hr.method).to.equal('POST');
          expect(hr.body).to.equal('Action=AssumeRoleWithWebIdentity&' + 'RoleArn=ARN&RoleSessionName=NAME&Version=' + service.api.apiVersion + '&WebIdentityToken=TOK');
          expect(hr.headers['Authorization']).to.equal(void 0);
          expect(hr.headers['Content-Type']).to.equal('application/x-www-form-urlencoded; charset=utf-8');
          return expect(hr.path).to.equal('/');
        });
      });
      return it('can build a post request on a mounted path (custom endpoint)', function() {
        var params;
        helpers.mockHttpResponse(200, {}, '{}');
        service = new AWS.STS({
          endpoint: 'http://localhost/foo/bar'
        });
        params = {
          RoleArn: 'ARN',
          RoleSessionName: 'NAME',
          WebIdentityToken: 'TOK'
        };
        return service.assumeRoleWithWebIdentity(params, function() {
          var hr;
          hr = this.request.httpRequest;
          expect(hr.path).to.equal('/foo/bar');
          return expect(hr.body).to.equal('Action=AssumeRoleWithWebIdentity&' + 'RoleArn=ARN&RoleSessionName=NAME&Version=' + service.api.apiVersion + '&WebIdentityToken=TOK');
        });
      });
    });
    return describe('assumeRoleWithSAML', function() {
      var service;
      service = new AWS.STS;
      return it('sends an unsigned POST request', function() {
        var params;
        helpers.mockHttpResponse(200, {}, '{}');
        params = {
          RoleArn: 'ARN',
          PrincipalArn: 'PARN',
          SAMLAssertion: 'OK'
        };
        return service.assumeRoleWithSAML(params, function() {
          var hr;
          hr = this.request.httpRequest;
          expect(hr.method).to.equal('POST');
          expect(hr.body).to.equal('Action=AssumeRoleWithSAML&' + 'PrincipalArn=PARN&RoleArn=ARN&SAMLAssertion=OK&' + 'Version=' + service.api.apiVersion);
          expect(hr.headers['Authorization']).to.equal(void 0);
          expect(hr.headers['Content-Type']).to.equal('application/x-www-form-urlencoded; charset=utf-8');
          return expect(hr.path).to.equal('/');
        });
      });
    });
  });

}).call(this);
