#!/usr/bin/env node

var fs = require('fs');

try {
	var changeFiles = fs.readdirSync(process.cwd() + '/.changes');
} catch (err) {
	if (err.code === 'ENOENT') {
		err.message += '. Make sure to run from sdk root directory';
	}
	throw err;
}

var updateScript = process.cwd() + '/scripts/update-changelog';
var changelogFile = process.cwd() + '/CHANGELOG.md';

var startContent = '# Changelog for AWS SDK for JavaScript\
\n<!--LATEST=0.0.0-->\
\n<!--ENTRYINSERT-->'

fs.writeFileSync(changelogFile, startContent);

var fileReg = /^(\d*)\.(\d*)\.(\d*)\.json$/;

changeFiles
	.map(function(file) { return file.match(fileReg); })
	.filter(function(version) { return !!version; })
	.sort(function(v1, v2) {
		var diff;
		for (var i = 1; i <= 3; i++) {
			diff = v1[i] - v2[i];
			if (diff !== 0) {
				return diff;
			}
		}
		return 0;
	})
	.map(function(version) { return version.slice(1).join('.'); })
	.forEach(function(version) {
		process.argv[2] = version;
		delete require.cache[updateScript];
		require(updateScript);
	});
